### ISSUE TITLE
Add option to remove random airport labels

### ISSUE THREAD

**Issue by fdrake97** [VATSIM-Radar/vatsim-radar#153]
### Your Vatsim CID

1664386

### What do you suggest?

Add option to remove these labels
![image](https://github.com/daniluk4000/vatsim-radar/assets/87662019/6c4c16c1-bd41-4594-9c7e-80dfc6801dee)

### Why do you need that?

clutters the map a bit too much, especially in areas with densely packed airports.

### Validation

- [X] I have searched for other requests and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by DotWallop** [comment]
Question is, what makes an airport "random"? Might be fixed with an option to display only a certain airport class. However that would only work in the US, as the rest of the world don't use airport classes the way the US does.

Another more innovative way would be to filter them out based on popularity... That might not be such a bad idea.

**Comment by daniluk4000** [comment]
> Question is, what makes an airport "random"? Might be fixed with an option to display only a certain airport class. However that would only work in the US, as the rest of the world don't use airport classes the way the US does.
> 
> Another more innovative way would be to filter them out based on popularity... That might not be such a bad idea.

They are not random though, it's all airports with traffic - like VatSpy

**Comment by fdrake97** [comment]
Should have said "unstaffed" instead of random. I just think it would be nice to have an option to toggle these off.
